env:
  global:
  - secure: MTzyOIQd3SBHbEsi7lFo+huNPKmOnQbFrhuaTJMs3DgU4yhtVYGWrLUci1q7opYS+DFG3f9SkhOjgk/vLXTz0UgI8cH1TjJsKcpOk73ANX7Negxnt0ydc5ujJg0WR/jDruFi4YL8GEy4lc8KAIoQ9EJE6JnULTvMU0/3V5dotIdMKf65VkJCrbmIv96EkLV0jiaSLYFsj3YEjYdp/sZ2OspL6mIvgDbdjpm83G247x5sqbCNSZIZOQa1QOm0x8iUvJhIQvuR/V3oRpgYCAMLbFvPmClJPeXa0Vh4drKrEVArpv+0h84vrNXhb+LtqGFwVs7HLFimzry089XoJVRe9TX4On/+h3zMxohVXyHCxkGYs1BJIfyHr1Nf3cn97Lipo938SMsJf/6mWCVZHllgidCce3OGE4aW6zynA4dfsfzvjpaYEqSbB6iRQzxcrBBhPkrpJmTzRXhBd5aIV6wf85pDFMaTmSm6DAmgdfJFC2tGDwauxZIt6hFrKvIsVRqapTZouLOZPX+0VmZQy6dwOmbyFDtdotMyU7Md9llYJdSUMc33MHM2mBtBK28UGLE0oVNpmHpkj6QZOLlCa1pF6AejbfscNAmGjHx18AQtpHubGuXW5593TjQ4I/SpJAnhKiQKp37ll32Jgme4ZbYlESH01deVdjLY83hVh4ddceQ=
  - secure: VqB5NRG1dVew6sAbphWil9BDVbFnIUHqt+YJnSXIe2hY7j/J5YAZlBp4QbWLTpNLq1KuonE0MiNGbh4QeErOwIhVtcpcKV4cFROkNHZT1BT4hdynHhTubwirDTdcicegRy4Wvb+aOfmuienwearaJTrmb/+tOL7EQEjXm8w4kmoYjq3ZPiGBFeNYqf1UU/6BZ8n8u/oM9pigK7BXfiU7oqBBTCM6ijTHypNPAFEBgd4GFZ3XxpuMOEYz/WzOcwN6mhcjhvDYv1HfdSOasr4SwWPDcSqjp4pFyEfrNYR3/JcT5YvcOyuxWgE9EV0IWc8zIxsbwX+z5YH6BxKtf5vuzIExY3SufOOE3g63ODdullbgdQ/fMAOc8yLrf5+w/p+G9JuJbIypCVMHXUYQmrQorrlJDT/U+hyxKZAriwo3iV/lwK7zApbzrMPcNs8H5Vr+7v33rBpQF0JKRnwlXpsTtG7OnkosadLsox0Y2UI+Acx2MlVGsN4h7r3Fu7SQtQU4cQOYdyLfcfwCI1j21Gy+7p9LA6gQK4qKaJSYSr4Wel3M+d6S+6i2Ok0Dt15VnKD2OusXJDyLdbPECPSjw81wcuNysfy3wgw4AOPDlPQFrF2efbq/OZ07BiWyVb9bFL8Gc5tG0wnRouvZb1SWfPzn5wxmH23vYFfB99zOacvf6W4=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8c33a1ba2f92_key -iv $encrypted_8c33a1ba2f92_iv
  -in config.json.enc -out config.json -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- echo 'I should write some tests...'
after_success:
- eval $(aws ecr get-login --region eu-west-1)
- docker build -t taco-bot/commands:latest -t taco-bot/commands:1.0.$TRAVIS_BUILD_NUMBER .
- docker tag taco-bot/commands:latest 869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot/commands:latest
- docker push 869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot/commands:latest
